### ISSUE TITLE
JSLint conflicts with SublimeLinter-jslint

### ISSUE THREAD

**Issue by Amparose** [devdoc/SublimeLinter-jslint#4]
The reporting in the editor does not match what I get running JSLint directly (ctrl + L) and seems mostly wrong. I have SublimeLinter v3.5 installed.

Example 1: http://pasteboard.co/1x6OEg2Z.png

I have all default settings, which means "--indent", "2". So not sure why JSLint through SumblineLinter is asking for 4 spaces.

Example 2: http://pasteboard.co/1x748lvh.png

Once again running JSLint directly reports no errors. Through SublimeLinter I get an use strict error and a request to move the closing curly bracket to col 5, which makes no sense!

Originally incorrectly posted [here](https://github.com/SublimeLinter/SublimeLinter3/issues/290#issuecomment-116163180).

**Comment by devdoc** [comment]
Hi,

The original JSLint (both [old](http://old.jslint.com) and [new](http://jslint.com) versions) by Douglas Crockford uses 4 spaces as indentation, and so does the [jslint](https://www.npmjs.com/package/jslint) npm package which is what SublimeLinter-jslint uses for linting. SublimeLinter-jslint does not alter default settings, so if you are running with default settings, I would say you are encountering expected behavior.

I suspect you may be looking at the settings file for another JSLint plugin ([perhaps this one](https://github.com/73rhodes/Sublime-JSLint/blob/master/JSLint.sublime-settings)), which changes defaults to indentation at 2 spaces and tolerates missing "use strict" statements. That settings file is only for that specific JSLint plugin, and does not affect how SublimeLinter-jslint operates. Settings for SublimeLinter should be in Packages/User/SublimeLinter.sublime-settings (you can open them up easily in Sublime text: Tools > SublimeLinter > Open User settings. In that file should be a section for jslint, which is where SublimeLinter-jslint looks for global default settings. You can also specify per-directory or per-file settings by using .jslintrc-files and inline directives.

Please [see here](https://github.com/devdoc/SublimeLinter-jslint#settings) for detailed instructions on how to change settings with SublimeLinter-jslint.

**Comment by Amparose** [comment]
Hi,

Thank you for the quick reply. It looks like I was getting myself confused as to which JSLint settings SublimeLinter was referring to. I have it under control now thanks to your message.
